# Generated by Django 5.1.4 on 2024-12-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asistenciaCtrl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='AttendanceModels',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyModels',
        ),
        migrations.RenameModel(
            old_name='Worker',
            new_name='WorkerModels',
        ),
    ]
