# Generated by Django 5.1.4 on 2024-12-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asistenciaCtrl', '0002_rename_attendance_attendancemodels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodels',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Establecimiento'),
        ),
    ]
