# Generated by Django 5.1.4 on 2024-12-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asistenciaCtrl', '0003_alter_companymodels_established_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodels',
            name='established_date',
            field=models.DateField(verbose_name='Fecha de Establecimiento'),
        ),
    ]
